# Generated by Django 5.0.6 on 2024-07-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_alter_profile_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='parti',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=100),
        ),
    ]
