# Generated by Django 5.0.6 on 2024-07-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
