# Generated by Django 5.0.6 on 2024-07-30 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_alter_expense_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='expense',
            new_name='expenses',
        ),
    ]
