# Generated by Django 5.0.6 on 2024-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_rename_expense_profile_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='method',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
